#!/cs/local/bin/bash


if [[ $# -ne 3 ]]
then
	printf "Usage: %s <gold-tab> <solution-tab> <simplified-tab>\n" ${0}
	printf "    <gold-tab>       : solution provided by KBP2016\n"
	printf "    <solution-tab>   : results generated by our system\n"
	printf "    <simplified-tab> : entries with file ID not in <gold-tab> are discarded\n"
fi

gold=${1}
sol=${2}
outfile=${3}

files=`cat ${gold} | cut -f4 | cut -d':' -f1 | sort | uniq`
for f in ${files}
do
	echo hopeless $f
done